[package]
name = "testutils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
toml = "0.5.9"
zstor_v2 = { path = "../" }
