[package]
name = "zdb-mon"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.21"
actix-web = "4.0.0-beta.8"
prometheus = "0.12"

[build-dependencies]
bindgen = "0.58"
