name: Release

on:
  release:
    types: [created]

jobs:
  build:
    name: Build release binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUSTTARGET: x86_64-unknown-linux-musl
          UPLOAD_MODE: release
          ARCHIVE_TYPES: tar.gz
          ARCHIVE_NAME: zstor_v2-x86_64-linux-musl.tar.gz
          SRC_DIR: zstor
