name: Release

on:
  release:
    types: [created]

jobs:
  release:
    name: Build release artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essentials musl-tools

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl
          override: true
      - run: cargo build --release --target x86_64-unknown-linux-musl --features vendored
      - run: strip target/x86_64-unknown-linux-musl/release/zstor
      - run: cp target/x86_64-unknown-linux-musl/release/zstor zstor_v2-x86_64-linux-musl

      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'zstor_v2-x86_64-linux-musl'
